config-version: 2

name: "brave_de_project"
version: "1.0.0"
require-dbt-version: ">=1.5.0"


profile: "brave_de_project" # Put your profile here

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  "dbt_date:time_zone": "America/Los_Angeles"

seeds:
  brave_de_project:
    +schema: raw

models:
  brave_de_project:
    database: BRAVE_DATABASE
    schema: PROJECT_TEST
    staging:
      +materialized: table
      +schema: staging
    raw_data:
      +materialized: table
    data_mart:
      +materialized: table
  +copy_grants: true

tests:
  +severity: warn  # Default severity level: warn
  
  # Classify tests by severity
  brave_de_project:
    # Critical data tests (error)
    data-tests:
      # Data integrity tests
      test_no_nulls_in_columns: {+severity: error}
      test_valid_user_ids: {+severity: error}
      test_valid_product_ids: {+severity: error}
      
      # Data consistency tests
      test_date_consistency_new: {+severity: error}
      test_stock_level_consistency_new: {+severity: error}
      
      # Business metrics tests
      test_inventory_metrics_calculation: {+severity: error}
      test_campaign_metrics_consistency: {+severity: error}
      test_conversion_rate_calculation: {+severity: error}
      test_key_metrics_stability: {+severity: error}
      
      # Non-critical tests (warn)
      test_valid_email: {+severity: warn}
