config-version: 2

name: "brave_de_project"
version: "1.0.0"
require-dbt-version: ">=1.5.0"


profile: my-snowflake-db # Put your profile here

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  "dbt_date:time_zone": "America/Los_Angeles"

seeds:
  brave_de_project:
    +schema: raw

models:
  brave_de_project:
    raw_data:
      +materialized: table
    staging:
      +materialized: view
    marts:
      +materialized: table

