brave_de_project:
  target: dev
  
  outputs:
    dev:
      type: snowflake
      account: pq32479.ca-central-1.aws

      # User/password auth
      user: PROJECT_LEARNER_BERNARD_A
      password: Lapel2177!!

      role: PROJECT_LEARNER_DE_READ
      database: BRAVE_DATABASE
      warehouse: BRAVE_WAREHOUSE
      schema: project_test
      threads: 1
      client_session_keep_alive: False
      query_tag: dbt

      # optional
      connect_retries: 1 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: False
