version: "3"

tasks:
  venv:
    cmds:
      - python -m venv .venv

  install:
    cmds:
      - python -m pip install --upgrade pip
      - python -m pip install --progress-bar off -- -r requirements.txt

  setup:
    cmds:
      - dbt deps
      - dbt seed
      # - rm -rf jaffle-data
