version: "3"

tasks:
  venv:
    cmds:
      - python3 -m venv .venv

  install:
    cmds:
      - python3 -m pip install --upgrade pip
      - python3 -m pip install --progress-bar off -- -r requirements.txt

  setup:
    desc: initial project setup
    cmds:
      - dbt deps
      - dbt seed
      - rm -rf jaffle-data
      - dbt run
      - dbt test

  t:
    desc: transform the data
    cmds:
      - dbt build --exclude resource_type:seed
      # we don't need to reseed the sample data,
      # this is much faster without them
