version: 2

models:
  - name: stg_inventory_data_PS
    description: "Staging table for inventory data."
    config:
      materialized: incremental
    columns:
      - name: inventory_id
        description: "Unique identifier for each inventory entry."
        tests:
          - unique
          - not_null
      - name: product_id
        description: "Identifier for the associated product."
        tests:
          - not_null
          - relationships:
              to: ref('stg_product_data_PS')
              field: product_id
      - name: quantity_in_stock
        description: "The quantity of the product available in stock."
        tests:
          - not_null
          - not_negative
      - name: inventory_status
        description: "The status of the inventory, e.g., 'in-stock' or 'backordered'."
        tests:
          - accepted_values:
              values: ['in-stock', 'backordered']
      - name: rating
        description: "Rating of the inventory, rounded to 1 decimal place."
        tests:
          - not_null
          - numeric
          - not_negative
      - name: weight
        description: "Weight of the product in inventory, rounded to 2 decimal places."
        tests:
          - not_null
          - numeric
          - not_negative
      - name: discounts
        description: "Discount percentage applied, rounded to 2 decimal places."
        tests:
          - numeric
          - not_negative

  - name: stg_product_data_PS
    description: "Staging table for product data."
    config:
      materialized: incremental
      unique_key: product_id
    columns:
      - name: product_id
        description: "Unique identifier for each product."
        tests:
          - unique
          - not_null
      - name: product_category
        description: "Category to which the product belongs."
        tests:
          - not_null
      - name: price
        description: "Price of the product."
        tests:
          - not_null
          - not_negative
      - name: weight_grams
        description: "Weight of the product in grams."
        tests:
          - not_null
          - numeric
          - not_negative
      - name: rating
        description: "Rating of the product, rounded to 1 decimal place."
        tests:
          - not_null
          - numeric
          - not_negative
      - name: discount_percentage
        description: "Discount percentage applied to the product."
        tests:
          - numeric
          - not_negative

  - name: stg_user_data_PS
    description: "Staging table for user data."
    config:
      materialized: incremental
    columns:
      - name: user_id
        description: "Unique identifier for each user."
        tests:
          - unique
          - not_null
      - name: email
        description: "Email address of the user."
      - name: account_status
        description: "Account status of the user, e.g., 'active', 'inactive', or 'banned'."
        tests:
          - accepted_values:
              values: ['active', 'inactive', 'banned']

  - name: stg_user_journey_PS
    description: "Staging table for user journey data."
    config:
      materialized: incremental
    columns:
      - name: search_event_id
        description: "Unique identifier for each search event."
        tests:
          - unique
          - not_null
      - name: user_id
        description: "Identifier for the user associated with the journey."
        tests:
          - not_null
      - name: product_id
        description: "Identifier for the product associated with the journey."
        tests:
          - not_null
      - name: has_atc
        description: "Indicates if the product was added to cart (true/false)."
        tests:
          - accepted_values:
              values: [true, false]
      - name: has_purchase
        description: "Indicates if the user made a purchase (true/false)."
        tests:
          - accepted_values:
              values: [true, false]
