version: 2

models:
  - name: stg_user_journey_bl  # Replace with your actual model name
    description: "staging table for user journey data"
    config:
      event_time: timestamp
    columns:
      - name: user_id
        description: "Unique identifier for the user"
        tests:
          - not_null
      - name: product_id
        description: "Unique identifier for the product"
        tests:
          - not_null
      - name: search_event_id
        description: "Unique identifier for the search event"
        tests:
          - not_null
      - name: cart_id
        description: "Unique identifier for the cart"
        tests:
          - not_null
      - name: session_id
        description: "Session identifier for the user interaction"
        tests:
          - not_null
      - name: timestamp
        description: "Timestamp of the event"
        tests:
          - not_null
      - name: search_terms
        description: "Terms used by user in the search"
      - name: search_results
        description: "Amount of results returned in the search"
      - name: search_type
        description: "Type of search used"
      - name: has_qv
        description: "Boolean flag indicating whether the user has viewed the product"
      - name: has_pdp
        description: "Boolean flag indicating whether the user has viewed the product detail page"
      - name: has_atc
        description: "Boolean flag indicating whether the user has added to cart"
      - name: has_purchase
        description: "Boolean flag indicating whether the user has made a purchase"
      - name: mkt_campaign
        description: "Name of marketing campaign"
      - name: mkt_content
        description: "Type of marketing content delivered to user"
      - name: mkt_medium
        description: "Method over which campaign was delivered to user"
      - name: mkt_source
        description: "Social site through which traffic was driven"
      - name: banner
        description: "Brand of store user shopped at"
      - name: selected_store_id
        description: "Identifier for the selected store"
      - name: fulfillment_type
        description: "Method which user selected for their order to be fulfilled"
      - name: app_id
        description: "App which user is using"
      - name: device_class
        description: "Type of device user is using"
      - name: geo_city
        description: "City user is located in"
      - name: geo_country
        description: "Country user is located in"
      - name: geo_latitude
        description: "Latitude of the user's location"
      - name: geo_longitude
        description: "Longitude of the user's location"
      - name: geo_region
        description: "Subnational region user is located in"
      - name: geo_timezone
        description: "Timezone user is located in"
      - name: geo_zipcode
        description: "Postal code serving the user's location"

  - name: stg_user_data_bl
    description: "Staging table for user data"
    config:
      event_time: signup_date
    columns:
      - name: user_id
        description: "Unique identifier for the user. Primary Key."
        tests:
          - not_null
      - name: first_name
        description: "User's first name"
      - name: last_name
        description: "User's last name"
      - name: email
        description: "User's email address"
      - name: signup_date
        description: "Registration date of user's account"
      - name: preferred_language
        description: "Preferred language of the user"
      - name: dob
        description: "User's date of birth"
      - name: marketing_opt_in
        description: "Boolean flag indicating whether the user has opted in to marketing info"
      - name: account_status
        description: "Activity status of the user (active, inactive, suspended)"
      - name: loyalty_points_balance
        description: "Amount of loyalty points in user's account"

  - name: stg_product_data_bl
    description: "Staging table for product data"
    config:
      event_time: manufacturing_date
      - name: product_id
        description: "Unique identifier for the product. Primary key"
      - name: product_name
        description: "Name of the product"
      - name: product_category
        description: "Category in which the product belongs"
      - name: price
        description: "Price of the product"
      - name: product_color
        description: "Color of the product"
      - name: manufacturing_date
        description: "Date when the product was manufactured"
      - name: expiration_date
        description: "Date when the product will expire"
      - name: warranty_period
        description: "warranty period of the product"
      - name: rating
        description: "Rating (1-5) of the product from users"
      - name: weight_grams
        description: "Weight, in grams, of the product"
      - name: discount_percentage
        description: "Discount, in %, applied to the product"
      
  - name: stg_inventory_data_bl
    description: "Staging table for inventory data"
    config:
      event_time: last_audit_date
      - name:
        description:
      - name:
        description:
      - name:
        description:
      - name:
        description:
      - name:
        description:
      