{{ config(materialized='table',unique_key='search_event_id') }}

WITH user_journey_cleaned AS (
   SELECT
       uj.SEARCH_EVENT_ID AS search_event_id,
       uj.TIMESTAMP AS timestamp,
       TO_TIMESTAMP_NTZ(uj.COLLECTOR_TSTAMP) AS collector_tstamp,
       uj.APP_ID AS app_id,
       uj.HAS_QV AS has_qv,
       uj.HAS_PDP AS has_pdp,
       uj.HAS_ATC AS has_atc,
       uj.HAS_PURCHASE AS has_purchase,
       uj.IMPRESSIONS_WITH_ATTRIBUTIONS AS impressions_with_attributions,
       uj.CART_ID AS cart_id,
       uj.SESSION_ID AS session_id,
       uj.SEARCH_REQUEST_ID AS search_request_id,
       uj.SEARCH_RESULTS_COUNT AS search_results_count,
       uj.SEARCH_TERMS AS search_terms,
       uj.SEARCH_FEATURE AS search_feature,
       uj.SEARCH_TERMS_TYPE AS search_terms_type,
       uj.SEARCH_TYPE AS search_type,
       uj.AES_HASH AS aes_hash,
       TO_DATE(uj.DATE_LAST_LOGIN) AS date_last_login,
       TO_DATE(uj.DATE_LAST_PURCHASE) AS date_last_purchase,
       uj.GROCERY_HOME_STORE_ID AS grocery_home_store_id,
       uj.LIFETIME_OFFLINE_ORDERS_COUNT AS lifetime_offline_orders_count,
       uj.LIFETIME_ONLINE_ORDERS_COUNT AS lifetime_online_orders_count,
       uj.LOGIN_STATUS AS login_status,
       uj.USER_ID AS user_id,
       uj.REGISTRATION_STATUS AS registration_status,
       uj.RX_HOME_STORE_ID AS rx_home_store_id,
       uj.SHA256_HASH AS sha256_hash,
       uj.BANNER AS banner,
       uj.AUTO_LOCALIZED_STORE_ID AS auto_localized_store_id,
       uj.FULFILLMENT_TYPE AS fulfillment_type,
       uj.SELECTED_STORE_ID AS selected_store_id,
       TO_DATE(uj.SELECTED_TIMESLOT_DATE) AS selected_timeslot_date,
       uj.SELECTED_TIMESLOT_TIME AS selected_timeslot_time,
       uj.SELECTED_TIMESLOT_TYPE AS selected_timeslot_type,
       uj.SHOPPING_MODE AS shopping_mode,
       uj.DEVICE_CLASS AS device_class,
       uj.BR_VIEWWIDTH AS br_viewwidth,
       uj.BR_VIEWHEIGHT AS br_viewheight,
       uj.DVCE_SCREENWIDTH AS dvce_screenwidth,
       uj.DVCE_SCREENHEIGHT AS dvce_screenheight,
       uj.DOC_WIDTH AS doc_width,
       uj.DOC_HEIGHT AS doc_height,
       uj.MKT_MEDIUM AS mkt_medium,
       uj.MKT_SOURCE AS mkt_source,
       uj.MKT_CONTENT AS mkt_content,
       uj.MKT_CAMPAIGN AS mkt_campaign,
       uj.BR_LANG AS br_lang,
       uj.PAGE_LANGUAGE AS page_language,
       uj.GEO_COUNTRY AS geo_country,
       uj.GEO_REGION AS geo_region,
       uj.GEO_CITY AS geo_city,
       uj.GEO_ZIPCODE AS geo_zipcode,
       uj.GEO_LATITUDE AS geo_latitude,
       uj.GEO_LONGITUDE AS geo_longitude,
       uj.GEO_TIMEZONE AS geo_timezone,
       uj.SEARCH_MODEL AS search_model,
       uj.PRODUCT_ID AS product_id
   FROM {{ source('de_project', 'user_journey') }} uj
   WHERE uj.SEARCH_EVENT_ID IS NOT NULL
)

SELECT * FROM user_journey_cleaned