{{
  config(
    materialized = 'table',
    unique_key = ['MKT_CAMPAIGN', 'MKT_MEDIUM', 'MKT_SOURCE', 'MKT_CONTENT']
  )
}}

SELECT 
  MKT_CAMPAIGN,
  MKT_MEDIUM,
  MKT_SOURCE,
  MKT_CONTENT,
  COUNT(DISTINCT SEARCH_EVENT_ID) AS TOTAL_SEARCH_EVENTS,
  COUNT(DISTINCT PRODUCT_ID) AS TOTAL_PRODUCTS,
  COUNT(CASE WHEN HAS_PURCHASE THEN 1 END) AS TOTAL_PURCHASES,
  COUNT(CASE WHEN HAS_ATC THEN 1 END) AS TOTAL_ADD_TO_CART,
  COUNT(CASE WHEN HAS_PDP THEN 1 END) AS TOTAL_PRODUCT_DETAIL_PAGES,
  COUNT(CASE WHEN HAS_PURCHASE THEN 1 END) * 1.0 / NULLIF(COUNT(DISTINCT SEARCH_EVENT_ID), 0) AS CONVERSION_RATE
FROM 
  {{ ref('view_user_journey_transformed_gs') }}
WHERE 
  MKT_CAMPAIGN IS NOT NULL
  AND MKT_MEDIUM IS NOT NULL
  AND MKT_SOURCE IS NOT NULL
  AND MKT_CONTENT IS NOT NULL
GROUP BY 
  MKT_CAMPAIGN,
  MKT_MEDIUM,
  MKT_SOURCE,
  MKT_CONTENT
