version: 2

models:
  - name: dim_inventory_tf
    description: "Dimension table for inventory"
    columns:
      - name: inventory_id
        description: "Primary key"
        tests:
          - not_null
          - unique
      - name: safety_stock_level
        description: "Safety stock threshold"
      - name: restock_point
        description: "Reorder point threshold"
      - name: unit_price
        description: "Unit price of the product"

  - name: dim_product_tf
    description: "Dimension table for products"
    columns:
      - name: product_id
        description: "Primary key"
        tests:
          - not_null
          - unique
      - name: product_category
        description: "Category of the product"

  - name: dim_user_tf
    description: "Dimension table for users"
    columns:
      - name: user_id
        description: "Primary key"
        tests:
          - not_null
          - unique
      - name: email
        description: "Email of the user"
      - name: signup_date
        description: "Date when the user signed up"
      - name: first_name
        description: "User's first name"
      - name: last_name
        description: "User's last name"
      - name: preferred_language
        description: "User's preferred language"
      - name: dob
        description: "User's date of birth"
      - name: marketing_opt_in
        description: "Whether the user has opted in for marketing"
      - name: account_status
        description: "Current status of the user's account"
      - name: loyalty_points_balance
        description: "User's loyalty points balance"

  - name: dim_campaign_tf
    description: "Dimension table for marketing campaigns"
    columns:
      - name: campaign_id
        description: "Primary key - Identifier for the marketing campaign"
        tests:
          - not_null
          - unique:
              severity: warn
      - name: campaign_source
        description: "Source of the marketing campaign"
      - name: campaign_medium
        description: "Medium of the marketing campaign"
      - name: campaign_content
        description: "Content of the marketing campaign"
      - name: target_country
        description: "Country targeted by the campaign"
      - name: target_region
        description: "Region targeted by the campaign"
      - name: target_device
        description: "Device type targeted by the campaign"
      - name: campaign_language
        description: "Language of the campaign"
      - name: campaign_name
        description: "Name of the campaign"
      - name: budget
        description: "Budget allocated for the campaign"
      - name: start_date
        description: "Start date of the campaign"
      - name: end_date
        description: "End date of the campaign"
      - name: campaign_objective
        description: "Objective of the campaign"
      - name: target_audience
        description: "Target audience of the campaign"
      - name: campaign_type
        description: "Type of campaign"
      - name: campaign_status
        description: "Current status of the campaign"
      - name: last_updated
        description: "Timestamp when the campaign data was last updated"

  - name: dim_search_terms_tf
    description: "Dimension table for search terms"
    columns:
      - name: search_request_id
        description: "Primary key - Unique identifier for the search request"
        tests:
          - not_null
          - unique:
              severity: warn
      - name: search_terms
        description: "The search terms used in the request"
        tests:
          - not_null
      - name: search_terms_type
        description: "Type of search terms (e.g., product, category)"
      - name: search_type
        description: "Type of search (e.g., text, voice, image)"
      - name: search_feature
        description: "Feature used for search (e.g., search bar, recommendation)"
      - name: search_model
        description: "Search model or algorithm used"
      - name: first_seen_at
        description: "Timestamp when this search term was first seen"
      - name: last_updated_at
        description: "Timestamp when this search term was last updated"

  - name: fact_campaign_metrics_tf
    description: "Fact table for aggregated campaign metrics by date"
    columns:
      - name: campaign_id
        description: "Identifier for the marketing campaign"
        tests:
          - not_null
          - relationships:
              to: ref('dim_campaign_tf')
              field: campaign_id
      - name: date_key
        description: "Date of the events"
        tests:
          - not_null
      - name: session_count
        description: "Total number of sessions for this campaign and date"
        tests:
          - not_null
      - name: purchase_count
        description: "Number of purchases for this campaign and date"
        tests:
          - not_null
      - name: total_revenue
        description: "Total revenue generated from purchases"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"
      - name: impression_count
        description: "Number of ad impressions"
        tests:
          - not_null
      - name: click_count
        description: "Number of ad clicks"
        tests:
          - not_null

  - name: fact_inventory_metrics_tf
    description: "Fact table for inventory metrics analysis"
    columns:
      - name: inventory_id
        description: "Primary key - Unique identifier for inventory item"
        tests:
          - not_null
          - relationships:
              to: ref('stg_inventory_data_tf')
              field: inventory_id
      - name: product_id
        description: "Foreign key to dim_product - Identifies which product this inventory item belongs to"
        tests:
          - not_null
          - relationships:
              to: ref('dim_product_tf')
              field: product_id
      - name: last_audit_date
        description: "Date of the last inventory audit"
        tests:
          - not_null
      - name: current_stock_level
        description: "Current stock level"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"
      - name: average_monthly_demand
        description: "Average monthly demand for inventory planning"
        tests:
          - not_null
      - name: stock_level_status
        description: "Status of stock level (e.g., 'Valid', 'Warning: Below Safety Stock', 'Warning: Below Reorder Level')"
        tests:
          - not_null

  - name: fact_search_metrics_tf
    description: "Fact table for analyzing search effectiveness and conversion rates"
    columns:
      - name: search_event_id
        description: "Unique identifier for the search event"
        tests:
          - not_null
          - unique
      - name: user_id
        description: "Foreign key to dim_user"
        tests:
          - not_null
          - relationships:
              to: ref('dim_user_tf')
              field: user_id
      - name: product_id
        description: "Foreign key to dim_product"
        tests:
          - not_null
          - relationships:
              to: ref('dim_product_tf')
              field: product_id
      - name: date_key
        description: "Date of the search event"
        tests:
          - not_null
      - name: search_request_id
        description: "Foreign key to dim_search_terms"
        tests:
          - not_null
          - relationships:
              to: ref('dim_search_terms_tf')
              field: search_request_id
      - name: campaign_id
        description: "Foreign key to dim_campaign - Identifies which campaign influenced the search behavior"
        tests:
          - relationships:
              to: ref('dim_campaign_tf')
              field: campaign_id
      - name: has_atc
        description: "Whether the search led to an add-to-cart event"
      - name: has_pdp
        description: "Whether the search led to a product detail page view"
      - name: has_qv
        description: "Whether the search led to a quick view"
      - name: has_purchase
        description: "Whether the search led to a purchase"

  - name: fact_product_performance_tf
    description: "Fact table for individual product purchase records"
    columns:
      - name: product_id
        description: "Foreign key to dim_product"
        tests:
          - not_null
          - relationships:
              to: ref('dim_product_tf')
              field: product_id
      - name: user_id
        description: "Foreign key to dim_user - Identifies which user made the purchase"
        tests:
          - not_null
          - relationships:
              to: ref('dim_user_tf')
              field: user_id
      - name: date_key
        description: "Date of the purchase event"
        tests:
          - not_null
      - name: has_purchase
        description: "Flag indicating this is a purchase event (always true)"
        tests:
          - not_null
          - accepted_values:
              values: [true]
      - name: purchase_count
        description: "Number of purchases for this product and date"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0"
      - name: revenue
        description: "Revenue generated from this purchase"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"
