version: 2

models:
  - name: dim_user_data_gs
    description: "Dimension table for user information."
    columns:
      - name: user_id
        tests:
          - unique
          - not_null

  - name: user_data_transformed_gs
    description: "Transformed user data with cleaned email and formatted dates."
    columns:
      - name: user_id
        tests:
          - unique
          - not_null


  - name: dim_inventory_data_gs
    description: "Dimension table storing inventory details."
    columns:
      - name: INVENTORY_ID
        tests:
          - unique
          - not_null
      - name: UPDATED_AT
        tests:
          - not_null

  - name: product_data_transformed_gs
    description: "Transformed product data from source."
    columns:
      - name: product_id
        tests:
          - unique
          - not_null

  - name: dim_product_data_gs
    description: "Dimension table storing product details."
    columns:
      - name: product_id
        tests:
          - unique
          - not_null
      - name: price
        tests:
          - not_null
      - name: updated_at
        tests:
          - not_null

  - name: user_journey_transformed_gs
    description: "Cleansed user journey data."
    columns:
      - name: search_event_id
        tests:
          - unique
          - not_null
      - name: timestamp
        tests:
          - not_null
      - name: user_id
        tests:
          - not_null

  - name: fact_product_performance_gs
    description: "Aggregated performance metrics for products."
    columns:
      - name: product_id
        tests:
          - not_null

  - name: fact_user_transactions_gs
    description: "Fact table storing user transactions."
    columns:
      - name: user_id
        tests:
          - not_null
      - name: search_event_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null
      - name: timestamp
        tests:
          - not_null

