version: 2

models:
  - name: dim_inventory
    description: "Dimension table for inventory"
    tests:
      - dbt_utils.expression_is_true:
          expression: "1=1"
          config:
            depends_on: [ref('stg_inventory_data')]
    columns:
      - name: inventory_id
        description: "Primary key"
        tests:
          - not_null
          - unique
      - name: quantity_in_stock
        tests:
          - not_null
      - name: total_inventory_value
        tests:
          - not_null

  - name: dim_product
    description: "Dimension table for products"
    tests:
      - dbt_utils.expression_is_true:
          expression: "1=1"
          config:
            depends_on: [ref('stg_product_data')]
    columns:
      - name: product_id
        description: "Primary key"
        tests:
          - not_null
          - unique

  - name: dim_user
    description: "Dimension table for users"
    tests:
      - dbt_utils.expression_is_true:
          expression: "1=1"
          config:
            depends_on: [ref('stg_user_data')]
    columns:
      - name: user_id
        description: "Primary key"
        tests:
          - not_null
          - unique
      - name: email
        tests:
          - dbt_utils.expression_is_true:
              expression: "email LIKE '%@%.%'"

  - name: dim_search_event
    description: "Dimension table for search events"
    tests:
      - dbt_utils.expression_is_true:
          expression: "1=1"
          config:
            depends_on: [ref('stg_user_journey')]
    columns:
      - name: search_event_id
        description: "Primary key"
        tests:
          - not_null
          - unique

  - name: fact_user_behavior_new
    description: "Combined fact table for user behavior including engagement and transactions"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - user_id
            - search_event_id
            - product_id
            - timestamp
          config:
            depends_on: [ref('dim_user'), ref('dim_product')]
    columns:
      - name: user_id
        description: "Foreign key to dim_user"
        tests:
          - not_null
      - name: product_id
        description: "Foreign key to dim_product"
        tests:
          - not_null
      - name: search_event_id
        description: "Identifier for the search event"
      - name: timestamp
        description: "Time of the event"
        tests:
          - not_null
      - name: has_qv
        description: "Flag indicating if user performed a quick view"
      - name: has_pdp
        description: "Flag indicating if user viewed product detail page"
      - name: has_atc
        description: "Flag indicating if user added product to cart"
      - name: has_purchase
        description: "Flag indicating if user purchased the product"
      - name: item_amount
        description: "Amount of the item if purchased"
      - name: funnel_stage
        description: "Stage in the purchase funnel (0-4)"
        tests:
          - dbt_utils.expression_is_true:
              expression: "funnel_stage >= 0 AND funnel_stage <= 4"

  - name: fact_campaign_metrics
    description: "Fact table for campaign performance analysis"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - campaign_id
            - date_key
          config:
            depends_on: [ref('dim_product')]
    columns:
      - name: campaign_id
        description: "Identifier for the marketing campaign"
        tests:
          - not_null
      - name: date_key
        description: "Date of the metrics"
        tests:
          - not_null
      - name: total_events
        description: "Total number of events"
        tests:
          - not_null
      - name: total_revenue
        description: "Total revenue from purchases"

  - name: fact_inventory_metrics_new
    description: "Fact table for inventory metrics analysis"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - product_id
            - warehouse_id
            - date_key
          config:
            depends_on: [ref('dim_inventory'), ref('dim_product')]
    columns:
      - name: product_id
        description: "Foreign key to dim_product"
        tests:
          - not_null
      - name: warehouse_id
        description: "Identifier for the warehouse"
        tests:
          - not_null
      - name: date_key
        description: "Date of the inventory metrics"
        tests:
          - not_null
      - name: current_stock_level
        description: "Current stock level"
        tests:
          - not_null
      - name: total_inventory_value
        description: "Total value of inventory"

  - name: fact_search_metrics_new
    description: "Fact table for analyzing search effectiveness and conversion rates"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - search_event_id
            - date_key
          config:
            depends_on: [ref('dim_search_event'), ref('dim_product')]
    columns:
      - name: search_event_id
        description: "Unique identifier for the search event"
        tests:
          - not_null
      - name: date_key
        description: "Date of the search event"
        tests:
          - not_null
      - name: search_results_count
        description: "Number of results returned by the search"
        tests:
          - not_null
      - name: total_searches
        description: "Total number of searches"
        tests:
          - not_null
