version: 2

models:
  - name: fact_user_engagement  # Replace with your actual model name
    description: "fact user engagement on user_id, product_id, serach_event_id, timestamp level"
    columns:
      - name: user_id
        description: "Unique identifier for the user"
        tests:
          - not_null
      - name: product_id
        description: "Unique identifier for the product"
        tests:
          - not_null
      - name: search_event_id
        description: "Unique identifier for the search event"
        tests:
          - not_null
      - name: timestamp
        description: "Timestamp of the event"
        tests:
          - not_null
      - name: has_qv
        description: "Boolean flag indicating whether the user has viewed the product"
      - name: has_pdp
        description: "Boolean flag indicating whether the user has viewed the product detail page"
      - name: has_atc
        description: "Boolean flag indicating whether the user has added to cart"
      - name: has_purchase
        description: "Boolean flag indicating whether the user has made a purchase"
      - name: session_id
        description: "Session identifier for the user interaction"
        tests:
          - not_null
