version: 2

models:
  - name: dim_product_sae
    description: "Dimension table for product details."
    columns:
      - name: product_id
        description: "Unique product identifier."
        tests:
          - not_null
          - unique
      - name: product_name
        description: "Standardized product name."
        tests:
          - not_null
      - name: product_category
        description: "Product category."
      - name: price
        description: "Product price, must be greater than 0."
        tests:
          - expression_is_true:
              expression: "price > 0"
      - name: rating
        description: "Product rating on a scale (e.g., 0 to 5)."
        tests:
          - expression_is_true:
              expression: "rating >= 0"
      - name: price_tier
        description: "Categorized price range: Low, Medium, or High."
      - name: trending_score
        description: "Calculated trending score based on rating and sales volume."

version: 2

models:
  - name: dim_user_sae
    description: "Dimension table for user data with derived attributes for segmentation."
    columns:
      - name: user_id
        description: "Unique user identifier."
        tests:
          - not_null
          - unique
      - name: first_name
        description: "User's first name."
        tests:
          - not_null
      - name: last_name
        description: "User's last name."
        tests:
          - not_null
      - name: full_name
        description: "User's full name derived from first and last name."
        tests:
          - not_null
      - name: email
        description: "User email address, standardized to lowercase."
        tests:
          - not_null
          - expression_is_true: { expression: "email REGEXP '^[a-z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{2,}$'" }
      - name: signup_date
        description: "Date when the user signed up."
        tests:
          - not_null
          - expression_is_true: { expression: "signup_date <= CURRENT_DATE()" }
      - name: preferred_language
        description: "User's preferred language."
      - name: dob
        description: "User's date of birth."
        tests:
          - expression_is_true: { expression: "dob IS NULL OR (dob >= '1900-01-01' AND dob <= CURRENT_DATE())" }
      - name: marketing_opt_in
        description: "Indicates whether the user opted into marketing (TRUE or FALSE)."
        tests:
          - expression_is_true: { expression: "marketing_opt_in IN (TRUE, FALSE)" }
      - name: account_status
        description: "User account status (e.g., Active, Inactive, Suspended)."
        tests:
          - not_null
      - name: loyalty_points_balance
        description: "User's loyalty points balance."
        tests:
          - expression_is_true: { expression: "loyalty_points_balance IS NULL OR loyalty_points_balance >= 0" }
      - name: load_timestamp
        description: "Timestamp when the record was loaded."
        tests:
          - not_null
      - name: age_years
        description: "Calculated age of the user in years."
        tests:
          - expression_is_true: { expression: "age_years IS NULL OR age_years >= 0" }
      - name: days_since_signup
        description: "Number of days since the user signed up."
        tests:
          - expression_is_true: { expression: "days_since_signup IS NULL OR days_since_signup >= 0" }

  - name: dim_campaign_sae
    description: "Dimension table for campaign details derived from user journey data."
    columns:
      - name: campaign_id
        description: "Surrogate key for the campaign."
        tests:
          - not_null
          - unique
      - name: campaign_name
        description: "Name of the campaign, standardized; 'No Campaign' for null entries."
        tests:
          - not_null
      - name: start_date
        description: "Earliest event timestamp for the campaign."
        tests:
          - not_null
      - name: end_date
        description: "Latest event timestamp for the campaign."
        tests:
          - not_null
          - expression_is_true: { expression: "end_date >= start_date" }

  - name: dim_search_terms_sae
    description: "Dimension table capturing search terms with popularity metrics, rate calculations, and an intent category."
    columns:
      - name: search_term_id
        description: "Surrogate key generated using ROW_NUMBER()."
        tests:
          - not_null
          - unique
      - name: search_term
        description: "Standardized search term, trimmed and lowercased."
        tests:
          - not_null
      - name: search_popularity
        description: "Total number of searches for the term."
        tests:
          - not_null
          - expression_is_true: { expression: "search_popularity >= 0" }
      - name: avg_results_count
        description: "Average number of search results returned for the term."
        tests:
          - not_null
          - expression_is_true: { expression: "avg_results_count >= 0" }
      - name: atc_rate
        description: "Rate of add-to-cart events for the term, as a fraction between 0 and 1."
        tests:
          - expression_is_true: { expression: "atc_rate IS NULL OR (atc_rate >= 0 AND atc_rate <= 1)" }
      - name: purchase_rate
        description: "Rate of purchase events for the term, as a fraction between 0 and 1."
        tests:
          - expression_is_true: { expression: "purchase_rate IS NULL OR (purchase_rate >= 0 AND purchase_rate <= 1)" }
      - name: intent_category
        description: "Categorized user intent for the search term (e.g., 'Buying', 'Considering', 'Browsing', 'Other')."
        tests:
          - not_null


  - name: fact_search_effect_sae
    description: "Fact table capturing individual user journey events for search effectiveness analysis."
    columns:
      - name: search_event_id
        description: "Unique identifier for each search event."
        tests:
          - not_null
          - unique
      - name: user_id
        description: "Foreign key referencing Dim_User."
        tests:
          - not_null
      - name: product_id
        description: "Foreign key referencing Dim_Product."
        tests:
          - not_null
      - name: search_date
        description: "The date extracted from the event timestamp."
        tests:
          - not_null
      - name: qv_count
        description: "Count of quick view events."
        tests:
          - not_null
      - name: pdp_count
        description: "Count of product detail page views."
        tests:
          - not_null
      - name: atc_count
        description: "Count of add-to-cart events."
        tests:
          - not_null
      - name: purchase_count
        description: "Count of purchase events."
        tests:
          - not_null
      - name: journey_score
        description: "Calculated score based on event weights."
        tests:
          - not_null
      - name: load_timestamp
        description: "Timestamp when the fact record was loaded."
        tests:
          - not_null

  - name: fact_product_perform_sae
    description: "Fact table aggregating product performance metrics by day."
    columns:
      - name: product_id
        description: "Foreign key referencing Dim_Product."
        tests:
          - not_null
      - name: search_date
        description: "Date when the interactions occurred."
        tests:
          - not_null
      - name: total_views
        description: "Total number of views (search events) for the product."
        tests:
          - not_null
      - name: atc_events
        description: "Number of add-to-cart events."
        tests:
          - not_null
      - name: purchase_events
        description: "Number of purchase events."
        tests:
          - not_null
      - name: last_updated
        description: "Timestamp when the fact record was last updated."
        tests:
          - not_null

  - name: fact_campaign_perform_sae
    description: "Fact table aggregating campaign performance metrics per day."
    columns:
      - name: campaign_id
        description: "Campaign identifier (derived from marketing campaign field)."
        tests:
          - not_null
      - name: search_date
        description: "Date when the campaign events occurred."
        tests:
          - not_null
      - name: total_interactions
        description: "Total number of interactions associated with the campaign."
        tests:
          - not_null
      - name: atc_events
        description: "Total add-to-cart events for the campaign."
        tests:
          - not_null
      - name: purchase_events
        description: "Total purchase events for the campaign."
        tests:
          - not_null
      - name: last_updated
        description: "Timestamp when the fact record was last updated."
        tests:
          - not_null

  - name: fact_inventory_mgt_sae
    description: "Fact table for inventory management, aggregating inventory metrics per product per warehouse per day."
    columns:
      - name: inventory_id
        description: "Unique inventory record identifier."
        tests:
          - not_null
      - name: product_id
        description: "Foreign key referencing Dim_Product."
        tests:
          - not_null
      - name: warehouse_id
        description: "Warehouse identifier (can join to Dim_Warehouse if available)."
        tests:
          - not_null
      - name: as_of_date
        description: "The date for which inventory is recorded (derived from restock_date)."
        tests:
          - not_null
      - name: stock_level
        description: "Current stock level."
        tests:
          - not_null
      - name: reorder_level
        description: "Reorder threshold."
        tests:
          - not_null
      - name: quantity_in_stock
        description: "Quantity available in stock."
        tests:
          - not_null
      - name: safety_stock
        description: "Minimum safety stock level."
        tests:
          - not_null
      - name: conversion_error_flag
        description: "Flag indicating data conversion errors."
        tests:
          - not_null
      - name: last_updated
        description: "Timestamp when the fact record was last updated."
        tests:
          - not_null




