version: 2

models:
  - name: dim_inventory_arsen_c
    description: "Dimensional table about inventory restocking. Each row represents a restocking of a certain product in a warehouse."
    columns:
      - name: inventory_id
        description: "Unique identifier for the restocking"
        data_tests:
          - not_null
          - unique
      - name: product_id
        description: "Unique identifier for the product"
        data_tests:
          - not_null
          - unique
      - name: warehouse_id
        description: "Unique identifier for the warehouset"
        data_tests:
          - not_null
          - unique
      - name: stock_level
        description: "Current stock of the item (or at the time of the row creation)"
        data_tests:
          - not_null
      - name: restock_date
        description: "The date which represents a specific restock"
        data_tests:
          - not_null
      - name: supplier_id
        description: "Supplier of the product to the warehouse"
        data_tests:
          - not_null
      - name: storage_condition
        description: "This field is supposed to show how to store the product"
        data_tests:
          - not_null
          - accepted_values:
              values: ['Ambient', 'Frozen', 'Temperature Controlled']
      
  - name: dim_product_arsen_c
    description: "fact user engagement on user_id, product_id, serach_event_id, timestamp level"
  - name: dim_search_event_arsen_c
    description: "fact user engagement on user_id, product_id, serach_event_id, timestamp level"
  - name: dim_user_arsen_c
    description: "fact user engagement on user_id, product_id, serach_event_id, timestamp level"
  - name: fact_aggregated_product_performance_arsen_c
    description: "fact user engagement on user_id, product_id, serach_event_id, timestamp level"
  - name: fact_campaign_effectiveness_arsen_c
    description: "fact user engagement on user_id, product_id, serach_event_id, timestamp level"
  - name: fact_demand_forecasting_arsen_c
    description: "fact user engagement on user_id, product_id, serach_event_id, timestamp level"
  - name: fact_inventory_condition_arsen_c
    description: "fact user engagement on user_id, product_id, serach_event_id, timestamp level"
  - name: fact_user_decisions_arsen_c
    description: "fact user engagement on user_id, product_id, serach_event_id, timestamp level"