version: 2

models:
  - name: dim_campaign_sae
    description: "Campaign dimension capturing campaign attributes from user journey data."
    columns:
      - name: campaign_id
        description: "Surrogate key for campaigns."
        tests:
          - not_null
          - unique
      - name: campaign_source
        description: "Source channel for the campaign."
        tests:
          - not_null
      - name: campaign_medium
        description: "Medium through which the campaign is delivered."
        tests:
          - not_null
      - name: campaign_content
        description: "Content details of the campaign."
      - name: target_country
        description: "Target country for the campaign."
      - name: target_region
        description: "Target region for the campaign."
      - name: target_device
        description: "Device type targeted (Mobile or Desktop)."
        tests:
          - accepted_values:
              values: ['Mobile', 'Desktop']
      - name: campaign_language
        description: "Language used in the campaign."
      - name: campaign_name
        description: "Friendly name for the campaign."
      - name: last_updated
        description: "Timestamp indicating when the campaign record was last updated."
        tests:
          - not_null

  - name: dim_product_sae
    description: "Product dimension capturing product attributes from product data."
    columns:
      - name: product_id
        description: "Surrogate key for products."
        tests:
          - not_null
          - unique
      - name: product_name
        description: "Name of the product."
        tests:
          - not_null
      - name: product_category
        description: "Category to which the product belongs."
      - name: price
        description: "List price of the product."
        tests:
          - not_null
          # You can replace the expression test below with a custom test if needed.
          - expression_is_true:
              expression: "price > 0"
      - name: rating
        description: "Product rating value."
        tests:
          - expression_is_true:
              expression: "rating >= 0 and rating <= 5"
      - name: sales_volume
        description: "Total sales volume for the product."
      - name: quantity_in_stock
        description: "Quantity of the product available in stock."
        tests:
          - expression_is_true:
              expression: "quantity_in_stock >= 0"
      - name: discount_percentage
        description: "Discount percentage applied to the product."
        tests:
          - expression_is_true:
              expression: "discount_percentage >= 0 and discount_percentage <= 100"
      - name: weight_grams
        description: "Product weight in grams."
        tests:
          - expression_is_true:
              expression: "weight_grams >= 0"
      - name: discounted_price
        description: "Calculated price after discount."
      - name: price_tier
        description: "Categorization of product based on price."
      - name: trending_score
        description: "Score combining rating and sales volume for trend analysis."
      - name: weight_category
        description: "Categorized bucket for product weight."
      - name: warranty_period
        description: "Warranty period description."
      - name: warranty_months
        description: "Warranty period in months."
      - name: product_age_days
        description: "Age of the product in days."
      - name: days_to_expiration
        description: "Days remaining until the product expires."
      - name: is_expired
        description: "Flag indicating if the product is expired."
      - name: load_timestamp
        description: "Timestamp of when the product record was loaded."
        tests:
          - not_null

  - name: dim_search_terms_sae
    description: "Search terms dimension aggregating search behavior metrics."
    columns:
      - name: search_term_id
        description: "Surrogate key for search terms."
        tests:
          - not_null
          - unique
      - name: search_term
        description: "The actual search term entered by users."
        tests:
          - not_null
      - name: search_popularity
        description: "Total number of searches for the term."
      - name: avg_results_count
        description: "Average number of results returned for the search term."
      - name: atc_rate
        description: "Rate at which users add to cart after searching."
        tests:
          - expression_is_true:
              expression: "atc_rate >= 0 and atc_rate <= 1"
      - name: purchase_rate
        description: "Rate at which users make a purchase after searching."
        tests:
          - expression_is_true:
              expression: "purchase_rate >= 0 and purchase_rate <= 1"
      - name: intent_category
        description: "Categorized user intent based on search behavior."

  - name: dim_user_sae
    description: "User dimension capturing customer details from user data."
    columns:
      - name: user_id
        description: "Surrogate key for users."
        tests:
          - not_null
          - unique
      - name: first_name
        description: "User's first name."
      - name: last_name
        description: "User's last name."
      - name: full_name
        description: "Concatenated full name of the user."
        tests:
          - not_null
      - name: email
        description: "User's email address."
        tests:
          - not_null
          - expression_is_true:
              expression: "email LIKE '%@%'"
      - name: signup_date
        description: "Date when the user signed up."
      - name: preferred_language
        description: "User's preferred language."
      - name: account_status
        description: "Current account status of the user."
        tests:
          - accepted_values:
              values: ['Active', 'Inactive', 'Suspended', 'Unknown']
      - name: marketing_opt_in
        description: "Flag indicating if the user opted into marketing."
      - name: age_years
        description: "User's age in years."
        tests:
          - expression_is_true:
              expression: "age_years >= 0"
      - name: days_since_signup
        description: "Number of days since the user signed up."
        tests:
          - expression_is_true:
              expression: "days_since_signup >= 0"
      - name: loyalty_points_balance
        description: "Current loyalty points balance for the user."
        tests:
          - expression_is_true:
              expression: "loyalty_points_balance >= 0"
      - name: load_timestamp
        description: "Timestamp of when the user record was loaded."
        tests:
          - not_null

  - name: fact_campaign_perform_sae
    description: "Campaign performance fact table aggregating search interactions for campaigns."
    columns:
      - name: campaign_id
        description: "Foreign key to dim_campaign_sae (campaign_id)."
        tests:
          - not_null
          # Removed dbt_utils.relationships test; consider creating a custom relationship test if needed.
      - name: search_date
        description: "Date when the campaign event occurred."
        tests:
          - not_null
      - name: total_interactions
        description: "Total number of campaign interactions."
        tests:
          - not_null
      - name: atc_events
        description: "Count of add-to-cart events for the campaign."
      - name: purchase_events
        description: "Count of purchase events for the campaign."
      - name: last_updated
        description: "Timestamp of the last update to the record."
        tests:
          - not_null

  - name: fact_inventory_mgt_sae
    description: "Inventory management fact table aggregating inventory metrics."
    columns:
      - name: inventory_id
        description: "Unique identifier for the inventory record."
        tests:
          - not_null
          - unique
      - name: product_id
        description: "Foreign key to dim_product_sae (product_id)."
        tests:
          - not_null
          # Removed dbt_utils.relationships test.
      - name: warehouse_id
        description: "Identifier for the warehouse."
        tests:
          - not_null
      - name: as_of_date
        description: "Date representing the inventory snapshot."
        tests:
          - not_null
      - name: stock_level
        description: "Inventory stock level."
      - name: reorder_level
        description: "Reorder level for the inventory."
      - name: quantity_in_stock
        description: "Quantity available in stock."
      - name: safety_stock
        description: "Safety stock value."
      - name: last_updated
        description: "Timestamp of the last record update."
        tests:
          - not_null
      - name: conversion_error_flag
        description: "Flag indicating conversion errors in the inventory record."

  - name: fact_product_perform_sae
    description: "Product performance fact table aggregating search interactions by product."
    columns:
      - name: product_id
        description: "Foreign key to dim_product_sae (product_id)."
        tests:
          - not_null
          # Removed dbt_utils.relationships test.
      - name: search_date
        description: "Date of the search event."
        tests:
          - not_null
      - name: total_views
        description: "Total number of product views."
        tests:
          - not_null
      - name: atc_events
        description: "Number of add-to-cart events for the product."
      - name: purchase_events
        description: "Number of purchase events for the product."
      - name: last_updated
        description: "Timestamp of the last update to the record."
        tests:
          - not_null

  - name: fact_search_effect_sae
    description: "Search effectiveness fact table aggregating search journey metrics."
    columns:
      - name: search_event_id
        description: "Unique identifier for the search event."
        tests:
          - not_null
          - unique
      - name: user_id
        description: "Foreign key to dim_user_sae (user_id)."
        tests:
          - not_null
          # Removed dbt_utils.relationships test.
      - name: product_id
        description: "Foreign key to dim_product_sae (product_id)."
        tests:
          - not_null
          # Removed dbt_utils.relationships test.
      - name: search_date
        description: "Date of the search event."
        tests:
          - not_null
      - name: last_event_timestamp
        description: "Timestamp of the last event in the search journey."
        tests:
          - not_null
      - name: qv_count
        description: "Count of quick view events."
      - name: pdp_count
        description: "Count of product detail page events."
      - name: atc_count
        description: "Count of add-to-cart events."
      - name: purchase_count
        description: "Count of purchase events."
      - name: journey_score
        description: "Calculated score summarizing the search journey."
      - name: load_timestamp
        description: "Timestamp when the record was loaded."
        tests:
          - not_null
      - name: search_term_id
        description: "Foreign key to dim_search_terms_sae (search_term_id)."
        tests:
          - not_null
          # Removed dbt_utils.relationships test.
      - name: search_term
        description: "Search term from the search event."
      - name: intent_category
        description: "Intent category from the search terms dimension."