version: 2

models:
  - name: fact_user_engagement  # Replace with your actual model name
    description: "fact user engagement on user_id, product_id, serach_event_id, timestamp level"
    columns:
      - name: user_id
        description: "Unique identifier for the user"
        tests:
          - not_null:
              config:
                severity: warn
      - name: product_id
        description: "Unique identifier for the product"
        tests:
          - not_null
      - name: search_event_id
        description: "Unique identifier for the search event"
        tests:
          - not_null
      - name: timestamp
        description: "Timestamp of the event"
        tests:
          - not_null
      - name: has_qv
        description: "Boolean flag indicating whether the user has viewed the product"
      - name: has_pdp
        description: "Boolean flag indicating whether the user has viewed the product detail page"
      - name: has_atc
        description: "Boolean flag indicating whether the user has added to cart"
      - name: has_purchase
        description: "Boolean flag indicating whether the user has made a purchase"
      - name: session_id
        description: "Session identifier for the user interaction"
        tests:
          - not_null


  - name: fact_product_performance_ba
    description: "Aggregates key performance metrics for each product, including views, ATC events, and purchases."
    columns:
      - name: product_id
        description: "Unique identifier for the product."
        tests: [unique, not_null]
      - name: product_name
        description: "Name of the product."
      - name: product_category
        description: "Category to which the product belongs."
      - name: price
        description: "Price of the product."
      - name: rating
        description: "Customer rating of the product."
      - name: discount_percentage
        description: "Current discount percentage on the product."
      - name: total_views
        description: "Total number of times the product was viewed."
      - name: total_atc_events
        description: "Total number of Add to Cart events for the product."
      - name: total_purchases
        description: "Total number of purchases of the product."
      - name: atc_rate_percentage
        description: "Percentage of views that led to an Add to Cart event."
      - name: purchase_rate_percentage
        description: "Percentage of views that resulted in a purchase."


  - name: campaign_effectiveness
    description: "Aggregates campaign performance metrics, including impressions, clicks, ATC events, and purchases."
    columns:
      - name: mkt_campaign
        description: "Marketing campaign name or identifier."
        tests: [not_null]
      - name: mkt_medium
        description: "Marketing medium (e.g., email, search, social)."
      - name: mkt_source
        description: "Source of the campaign traffic."
      - name: mkt_content
        description: "Additional context or ad creative description."
      - name: total_impressions
        description: "Total number of impressions for the campaign."
      - name: total_clicks
        description: "Total number of clicks or Quick Views."
      - name: total_atc_events
        description: "Total number of Add to Cart (ATC) events."
      - name: total_purchases
        description: "Total number of purchases resulting from the campaign."
      - name: total_revenue
        description: "Total revenue generated by the campaign."
      - name: atc_conversion_rate
        description: "Conversion rate from clicks to ATC events."
      - name: purchase_conversion_rate
        description: "Conversion rate from ATC events to purchases."
      - name: revenue_per_click
        description: "Average revenue per click."


  - name: inventory_summary
    description: "Aggregates inventory levels, stock status, and demand forecasting by product and warehouse."
    columns:
      - name: product_id
        description: "Unique identifier for the product."
        tests: [not_null]
      - name: product_name
        description: "Name of the product."
      - name: warehouse_id
        description: "Warehouse where the product is stored."
        tests: [not_null]
      - name: total_stock_level
        description: "Total quantity of stock available in the warehouse."
      - name: total_safety_stock
        description: "Minimum safety stock to prevent stockouts."
      - name: total_reorder_level
        description: "Stock level threshold to trigger restocking."
      - name: total_monthly_demand
        description: "Average monthly demand for the product."
      - name: next_restock_date
        description: "Next scheduled restock date."
      - name: last_restock_date
        description: "Last completed restock date."
      - name: stock_status
        description: "Stock status indicator (Reorder Required, Restock Soon, Sufficient Stock)."

        
  - name: dim_user_data_search_ba
    description: "Dimension table for user profiles"
    columns:
      - name: user_id
        tests: [unique, not_null]
      - name: account_status
        tests:
          - accepted_values:
              values: ['active', 'inactive', 'suspended']

  - name: dim_product_search_ba
    description: "Dimension table for product metadata"
    columns:
      - name: product_id
        tests: [unique, not_null]
      - name: product_category
      - name: price
      - name: discount_percentage

  - name: dim_geo_search_ba
    description: "Dimension table for geographic information"
    columns:
      - name: geo_country
      - name: geo_region
      - name: geo_city

  - name: dim_device_search_ba
    description: "Dimension table for device information"
    columns:
      - name: device_class
        tests:
          - accepted_values:
              values: ['mobile', 'desktop', 'tablet']

  - name: dim_marketing_search_ba
    description: "Dimension table for marketing attribution data"
    columns:
      - name: mkt_campaign
      - name: mkt_medium
      - name: mkt_source
      - name: mkt_content

  - name: dim_cart_search_ba
    description: "Dimension table for cart-level data"
    columns:
      - name: cart_id
        tests: [unique]
      - name: fulfillment_type
      - name: selected_store_id

  - name: dim_inventory_search_ba
    description: "Dimension table for product inventory and stock levels"
    columns:
      - name: inventory_item_key
        tests: [unique, not_null]
      - name: stock_level
      - name: reorder_level
      - name: safety_stock