version: 2

models:
  - name: dim_user_bl
    description: "Table for user data"
    columns:
      - name: user_id
        description: "Unique identifier for the user. Primary Key."
        tests:
          - not_null
      - name: first_name
        description: "User's first name"
      - name: last_name
        description: "User's last name"
      - name: email
        description: "User's email address"
      - name: signup_date
        description: "Registration date of user's account"
      - name: preferred_language
        description: "Preferred language of the user"
      - name: dob
        description: "User's date of birth"
      - name: marketing_opt_in
        description: "Boolean flag indicating whether the user has opted in to marketing info"
      - name: account_status
        description: "Activity status of the user (active, inactive, suspended)"
      - name: loyalty_points_balance
        description: "Amount of loyalty points in user's account"

  - name: dim_product_bl
    description: "Table for product data"
    columns:
      - name: product_id
        description: "Unique identifier for the product. Primary key"
        tests:
          - not_null
      - name: product_name
        description: "Name of the product"
      - name: product_category
        description: "Category in which the product belongs"
      - name: price
        description: "Price of the product"
      - name: product_color
        description: "Color of the product"
      - name: manufacturing_date
        description: "Date when the product was manufactured"
      - name: expiration_date
        description: "Date when the product will expire"
      - name: warranty_period
        description: "warranty period of the product"
      - name: rating
        description: "Rating (1-5) of the product from users"
      - name: weight_grams
        description: "Weight, in grams, of the product"
      - name: discount_percentage
        description: "Discount, in %, applied to the product"


  - name: fact_search_effectiveness_bl
    description: "Effectiveness of search by product"
    columns:
      - name: product_id
        description: "Unique identifier for the product"
        tests:
          - not_null
      - name: product_name
        description: "Name of the product"
      - name: views
        description: "Amount of times the product is viewed"
      - name: detail_views
        description: "Amount of times the product details page is viewed"
      - name: atc_events
        description: "Amount of times the product is added to cart"
      - name: purchases
        description: "Amount of times the product is purchased"
      - name: searches
        description: "Amount of searches related to the product"

  - name: fact_campaign_effectiveness_bl
    description: "Effectiveness of marketing campaigns for each medium and each geographic region"
    columns:
      - name: mkt_campaign
        description: "Unique identifier for the marketing campaign"
        tests:
          - not_null
      - name: mkt_content
        description: "Type of marketing content delivered to user"
      - name: mkt_medium
        description: "Method over which campaign was delivered to user"
      - name: mkt_source
        description: "Social site through which traffic was driven"
      - name: geo_country
        description: "Country campaign was deployed in"
      - name: geo_region
        description: "Subnational region campaign was deployed in"
      - name: views
        description: "Amount of views driven by the campaign"
      - name: detail_views
        description: "Amount of views of product details pages driven by the campaign"
      - name: atc_events
        description: "Amount of ATC (add to cart) events driven by the campaign"
      - name: purchases
        description: "Amount of purchases driven by the campaign"
      - name: revenue
        description: "Amount of revenue generated by the campaign"

  - name: fact_product_performance_bl
    description: "Performance of each product"
    columns:
      - name: product_id
        description: "Unique identifier for the product"
        tests:
          - not_null
      - name: product_name
        description: "Name of the product"
      - name: price
        description: "Price of the product"
      - name: views
        description: "Amount of times the product is viewed"
      - name: detail_views
        description: "Amount of times the product details page is viewed"
      - name: atc_events
        description: "Amount of times the product is added to cart"
      - name: purchases
        description: "Amount of times the product is purchased"

  - name: fact_inventory_bl
    description: "Table for inventory data"
    columns:
      - name: inventory_id
        description: "Unique identifier for the inventory item. Primary key"
        tests:
          - not_null
      - name: reorder_level
        description: "Quantity at which product should be reordered"
      - name: product_id
        description: "Unique identifier for the product"
      - name: quantity_in_stock
        description: "Quantity currently in stock"
      - name: warehouse_id
        description: "Unique identifier for the warehouse"
      - name: rating
        description: "Rating (1-5) of the product from users"
      - name: stock_level
        description: "Stock level"
      - name: sales_volume
        description: "Sales volume"
      - name: restock_date
        description: "Date of last restock"
      - name: supplier_id
        description: "Unique identifier for the supplier"
      - name: storage_condition
        description: "Condition under which inventory is stored"
      - name: safety_stock
        description: "Amount of safety stock"
      - name: inventory_status
        description: "Status of the inventory"
      - name: average_monthly_demand
        description: "Average monthly demand for the product"
      - name: last_audit_date
        description: "Date the inventory was last audited"
      - name: last_restock_date
        description: "Date of the previous restock"
      - name: next_restock_date
        description: "Date of the next restock"